spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      database: kalah
      authentication-database: admin
game:
  numberOfPits: 6
  numberOfStones: 6