server:
  port: 8080
  uri: http://localhost:8080/games/

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      username: root
      password: example
      database: kalah
      authentication-database: admin
game:
  numberOfPits: 6
  numberOfStones: 6
  gameSequenceName: game
